# Generated by Django 3.1.7 on 2021-06-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210512_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerelated',
            options={'verbose_name': '图片管理', 'verbose_name_plural': '图片管理'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-reorder'], 'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
