# Generated by Django 3.1.7 on 2021-05-12 13:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0002_auto_20210412_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-love_count', '-created_at'], 'verbose_name': '评论及回复', 'verbose_name_plural': '评论及回复'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '景点详情', 'verbose_name_plural': '景点详情'},
        ),
        migrations.AlterModelOptions(
            name='sight',
            options={'ordering': ['-updated_at'], 'verbose_name': '景点基础信息', 'verbose_name_plural': '景点基础信息'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '门票', 'verbose_name_plural': '门票'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='entry_explain',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='入院参考'),
        ),
        migrations.AlterField(
            model_name='info',
            name='play_way',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='特色玩法'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sight.sight', verbose_name='关联景点'),
        ),
        migrations.AlterField(
            model_name='info',
            name='tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='温馨提示'),
        ),
        migrations.AlterField(
            model_name='info',
            name='traffic',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='交通到达'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='详细'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='其他说明'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='预定须知'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
